apiVersion: v1
kind: Service
metadata:
  name: python-app-nodeport
  namespace: test-python
  labels:
    app: python-app
spec:
  selector:
    app: python-app
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
    nodePort: 30080
  type: NodePort

---
---
# Service for Flask Microservices (ClusterIP for Ingress)
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: test-python
  labels:
    app: python-app
    service: flask-microservices
spec:
  selector:
    app: python-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP